version: 0.12.{build}
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
image: Visual Studio 2022
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: nuget restore
build:
  parallel: true
  verbosity: normal
environment:
  github_access_token:
    secure: kjDyjFc99PloCToD7DfI3ETVarqB4gjDe8HNYHe8FojFVSDqjmX6XCxP77nzAzFR
artifacts:
- path: Rapr\bin\$(configuration)
  name: DriverStoreExplorer.v$(appveyor_build_version)
on_success:
- ps: Set-Content "$env:USERPROFILE\.git-credentials" "https://$($env:github_access_token)@github.com" -NoNewline
- cmd: >-
    git config credential.helper store
    && git tag v%appveyor_build_version%
    && git push origin v%appveyor_build_version%
