//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rapr.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rapr.Lang.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string About_Download {
            get {
                return ResourceManager.GetString("About_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Found New Version v{0} - {1}).
        /// </summary>
        public static string About_FoundNewVersion {
            get {
                return ResourceManager.GetString("About_FoundNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can find latest version and release notes here:
        ///    https://github.com/lostindark/DriverStoreExplorer/releases
        ///
        ///Filing bug/feature request:
        ///    https://github.com/lostindark/DriverStoreExplorer/issues
        ///
        ///Contributors:
        ///    https://github.com/lostindark/DriverStoreExplorer/graphs/contributors
        ///
        ///Credits:
        ///    ObjectListView http://objectlistview.sourceforge.net/
        ///    Managed DismApi Wrapper https://github.com/jeffkl/ManagedDism
        ///
        ///License:
        ///    https://github.com/lostindark/DriverStoreExplorer/blob/m [rest of string was truncated]&quot;;.
        /// </summary>
        public static string About_Project_Description {
            get {
                return ResourceManager.GetString("About_Project_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Up to date).
        /// </summary>
        public static string About_VersionUpToDate {
            get {
                return ResourceManager.GetString("About_VersionUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Add Driver.
        /// </summary>
        public static string Button_Add_Package {
            get {
                return ResourceManager.GetString("Button_Add_Package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cancel.
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Delete Driver(s).
        /// </summary>
        public static string Button_Delete_Package {
            get {
                return ResourceManager.GetString("Button_Delete_Package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Export Driver(s).
        /// </summary>
        public static string Button_Export_Drivers {
            get {
                return ResourceManager.GetString("Button_Export_Drivers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;OK.
        /// </summary>
        public static string Button_OK {
            get {
                return ResourceManager.GetString("Button_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Refresh.
        /// </summary>
        public static string Button_Refresh {
            get {
                return ResourceManager.GetString("Button_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select &amp;Old Driver(s).
        /// </summary>
        public static string Button_Select_Old {
            get {
                return ResourceManager.GetString("Button_Select_Old", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Deletio&amp;n.
        /// </summary>
        public static string Check_Force_Delete {
            get {
                return ResourceManager.GetString("Check_Force_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Install Driver.
        /// </summary>
        public static string Check_Install_Driver {
            get {
                return ResourceManager.GetString("Check_Install_Driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Choose Driver Store.
        /// </summary>
        public static string ChooseDriverStore_Title {
            get {
                return ResourceManager.GetString("ChooseDriverStore_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boot Critical.
        /// </summary>
        public static string Column_BootCritical {
            get {
                return ResourceManager.GetString("Column_BootCritical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver Date.
        /// </summary>
        public static string Column_Date {
            get {
                return ResourceManager.GetString("Column_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Name.
        /// </summary>
        public static string Column_DeviceName {
            get {
                return ResourceManager.GetString("Column_DeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver Class.
        /// </summary>
        public static string Column_Driver_Class {
            get {
                return ResourceManager.GetString("Column_Driver_Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INF.
        /// </summary>
        public static string Column_Inf {
            get {
                return ResourceManager.GetString("Column_Inf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OEM INF.
        /// </summary>
        public static string Column_Oem_Inf {
            get {
                return ResourceManager.GetString("Column_Oem_Inf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider.
        /// </summary>
        public static string Column_Provider {
            get {
                return ResourceManager.GetString("Column_Provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signed By.
        /// </summary>
        public static string Column_Signed_By {
            get {
                return ResourceManager.GetString("Column_Signed_By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string Column_Size {
            get {
                return ResourceManager.GetString("Column_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        public static string Column_Text_False {
            get {
                return ResourceManager.GetString("Column_Text_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        public static string Column_Text_True {
            get {
                return ResourceManager.GetString("Column_Text_True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver Version.
        /// </summary>
        public static string Column_Version {
            get {
                return ResourceManager.GetString("Column_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Context_Delete {
            get {
                return ResourceManager.GetString("Context_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Deselect.
        /// </summary>
        public static string Context_Deselect {
            get {
                return ResourceManager.GetString("Context_Deselect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deselect &amp;All.
        /// </summary>
        public static string Context_Deselect_All {
            get {
                return ResourceManager.GetString("Context_Deselect_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Export Driver.
        /// </summary>
        public static string Context_Export_Driver {
            get {
                return ResourceManager.GetString("Context_Export_Driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open &amp;Folder Location.
        /// </summary>
        public static string Context_Open_Folder {
            get {
                return ResourceManager.GetString("Context_Open_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Select.
        /// </summary>
        public static string Context_Select {
            get {
                return ResourceManager.GetString("Context_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select &amp;All.
        /// </summary>
        public static string Context_Select_All {
            get {
                return ResourceManager.GetString("Context_Select_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select &amp;Old Drivers.
        /// </summary>
        public static string Context_Select_Old {
            get {
                return ResourceManager.GetString("Context_Select_Old", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:d}.
        /// </summary>
        public static string Date_Format {
            get {
                return ResourceManager.GetString("Date_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV Files | *.csv.
        /// </summary>
        public static string Dialog_Export_Filters {
            get {
                return ResourceManager.GetString("Dialog_Export_Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the INF.
        /// </summary>
        public static string Dialog_Open_Filter_Text {
            get {
                return ResourceManager.GetString("Dialog_Open_Filter_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INF files | *.inf.
        /// </summary>
        public static string Dialog_Open_Filters {
            get {
                return ResourceManager.GetString("Dialog_Open_Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Machine.
        /// </summary>
        public static string DriverStore_LocalMachine {
            get {
                return ResourceManager.GetString("DriverStore_LocalMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline Driver Store.
        /// </summary>
        public static string DriverStore_Offline {
            get {
                return ResourceManager.GetString("DriverStore_Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contents saved to {0}. Export Completed..
        /// </summary>
        public static string Export_Complete {
            get {
                return ResourceManager.GetString("Export_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Export_Error {
            get {
                return ResourceManager.GetString("Export_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export failed: {0}.
        /// </summary>
        public static string Export_Failed {
            get {
                return ResourceManager.GetString("Export_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;File.
        /// </summary>
        public static string Menu_File {
            get {
                return ResourceManager.GetString("Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Choose Driver Store.
        /// </summary>
        public static string Menu_File_Choose_Driver_Store {
            get {
                return ResourceManager.GetString("Menu_File_Choose_Driver_Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E&amp;xit.
        /// </summary>
        public static string Menu_File_Exit {
            get {
                return ResourceManager.GetString("Menu_File_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Export Driver List.
        /// </summary>
        public static string Menu_File_Export {
            get {
                return ResourceManager.GetString("Menu_File_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ex&amp;port All Drivers.
        /// </summary>
        public static string Menu_File_Export_All_Drivers {
            get {
                return ResourceManager.GetString("Menu_File_Export_All_Drivers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;View Logs.
        /// </summary>
        public static string Menu_File_View_Logs {
            get {
                return ResourceManager.GetString("Menu_File_View_Logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Help.
        /// </summary>
        public static string Menu_Help {
            get {
                return ResourceManager.GetString("Menu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;About.
        /// </summary>
        public static string Menu_Help_About {
            get {
                return ResourceManager.GetString("Menu_Help_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Language.
        /// </summary>
        public static string Menu_Language {
            get {
                return ResourceManager.GetString("Menu_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletion of {0} ({1}) failed..
        /// </summary>
        public static string Message_Delete_Fail {
            get {
                return ResourceManager.GetString("Message_Delete_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About to delete {0} packages from driver store..
        /// </summary>
        public static string Message_Delete_Multiple_Packages {
            get {
                return ResourceManager.GetString("Message_Delete_Multiple_Packages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed {0} ({1}) from driver store..
        /// </summary>
        public static string Message_Delete_Package {
            get {
                return ResourceManager.GetString("Message_Delete_Package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error removing {0} ({1}) from driver store..
        /// </summary>
        public static string Message_Delete_Package_Error {
            get {
                return ResourceManager.GetString("Message_Delete_Package_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed {0} packages from driver store..
        /// </summary>
        public static string Message_Delete_Packages {
            get {
                return ResourceManager.GetString("Message_Delete_Packages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error removing some packages from driver store..
        /// </summary>
        public static string Message_Delete_Packages_Error {
            get {
                return ResourceManager.GetString("Message_Delete_Packages_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About to delete {0} ({1}) from driver store..
        /// </summary>
        public static string Message_Delete_Single_Package {
            get {
                return ResourceManager.GetString("Message_Delete_Single_Package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletion of {0} ({1}) succeeded..
        /// </summary>
        public static string Message_Delete_Success {
            get {
                return ResourceManager.GetString("Message_Delete_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added the package {0} to driver store..
        /// </summary>
        public static string Message_Driver_Added {
            get {
                return ResourceManager.GetString("Message_Driver_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error adding {0} the package to driver store..
        /// </summary>
        public static string Message_Driver_Added_Error {
            get {
                return ResourceManager.GetString("Message_Driver_Added_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added the package {0} &amp; installed to driver store..
        /// </summary>
        public static string Message_Driver_Added_Installed {
            get {
                return ResourceManager.GetString("Message_Driver_Added_Installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error adding the package {0} &amp; installed to driver store..
        /// </summary>
        public static string Message_Driver_Added_Installed_Error {
            get {
                return ResourceManager.GetString("Message_Driver_Added_Installed_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Message_Error {
            get {
                return ResourceManager.GetString("Message_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export all driver packages failed..
        /// </summary>
        public static string Message_Export_All_Drivers_Fail {
            get {
                return ResourceManager.GetString("Message_Export_All_Drivers_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export all driver packages succeeded..
        /// </summary>
        public static string Message_Export_All_Drivers_Success {
            get {
                return ResourceManager.GetString("Message_Export_All_Drivers_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About to force delete {0} packages from driver store..
        /// </summary>
        public static string Message_ForceDelete_Multiple_Packages {
            get {
                return ResourceManager.GetString("Message_ForceDelete_Multiple_Packages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About to force delete {0} ({1}) from driver store..
        /// </summary>
        public static string Message_ForceDelete_Single_Package {
            get {
                return ResourceManager.GetString("Message_ForceDelete_Single_Package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The log file cannot be found..
        /// </summary>
        public static string Message_Log_File_NotFound {
            get {
                return ResourceManager.GetString("Message_Log_File_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No entries loaded..
        /// </summary>
        public static string Message_No_Entries {
            get {
                return ResourceManager.GetString("Message_No_Entries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This utility cannot be run in pre-Vista OS..
        /// </summary>
        public static string Message_Requires_Later_OS {
            get {
                return ResourceManager.GetString("Message_Requires_Later_OS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning driver store....
        /// </summary>
        public static string Message_Scanning_Driver_Store {
            get {
                return ResourceManager.GetString("Message_Scanning_Driver_Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string Message_Sure {
            get {
                return ResourceManager.GetString("Message_Sure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Message_Title_Warning {
            get {
                return ResourceManager.GetString("Message_Title_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations.
        /// </summary>
        public static string Operations_Text {
            get {
                return ResourceManager.GetString("Operations_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About {0}.
        /// </summary>
        public static string Product_About_Title {
            get {
                return ResourceManager.GetString("Product_About_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver Store Explorer.
        /// </summary>
        public static string Product_Name {
            get {
                return ResourceManager.GetString("Product_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding driver package....
        /// </summary>
        public static string Status_Adding_Package {
            get {
                return ResourceManager.GetString("Status_Adding_Package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting driver package(s)....
        /// </summary>
        public static string Status_Deleting_Packages {
            get {
                return ResourceManager.GetString("Status_Deleting_Packages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting all driver packages....
        /// </summary>
        public static string Status_Exporting_All_Drivers {
            get {
                return ResourceManager.GetString("Status_Exporting_All_Drivers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string Status_Label {
            get {
                return ResourceManager.GetString("Status_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No drivers selected..
        /// </summary>
        public static string Status_No_Drivers_Selected {
            get {
                return ResourceManager.GetString("Status_No_Drivers_Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected {0} Driver(s). Total size: {1}..
        /// </summary>
        public static string Status_Selected_Drivers {
            get {
                return ResourceManager.GetString("Status_Selected_Drivers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [TIP: The driver may still being used. Try FORCE deleting the package].
        /// </summary>
        public static string Tip_Driver_In_Use {
            get {
                return ResourceManager.GetString("Tip_Driver_In_Use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string UnitTest_Language {
            get {
                return ResourceManager.GetString("UnitTest_Language", resourceCulture);
            }
        }
    }
}
